// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class BatterySession
{
    public int SessionId { get; set; }

    public string BatteryId { get; set; }

    public decimal? SocStart { get; set; }

    public decimal? SocEnd { get; set; }

    public decimal? CycleStart { get; set; }

    public decimal? CycleEnd { get; set; }

    public decimal? EnergyChargedWh { get; set; }

    public decimal? EnergyDischargedWh { get; set; }

    public DateTime? TimestampOut { get; set; }

    public DateTime? TimestampIn { get; set; }

    public virtual Battery Battery { get; set; }
}