// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class PillarSlot
{
    public int SlotId { get; set; }

    public string BatterySwapPillarId { get; set; }

    public string BatteryId { get; set; }

    public int SlotNumber { get; set; }

    public string Status { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual BatterySwapPillar BatterySwapPillar { get; set; }
}