// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoltSwap.DAL.Models;

public partial class Transaction
{
    public string TransactionId { get; set; }

    public string SubscriptionId { get; set; }

    public string UserDriverId { get; set; }

    public string TransactionType { get; set; }

    public decimal? Amount { get; set; }

    public string Currency { get; set; }

    public DateTime TransactionDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public decimal? Fee { get; set; }

    public decimal TotalAmount { get; set; }

    public string Note { get; set; }

    public virtual Subscription Subscription { get; set; }

    public virtual User UserDriver { get; set; }
}